apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo
          args:
            - "-text=Config loaded: ENV=$(APP_ENV)"
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: APP_ENV
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: API_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: PORT