---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html

    - name: content-creator
      image: busybox
      command: ["/bin/sh"]
      args:
        - -c
        - while true; do date > /html/index.html; sleep 10; done
      volumeMounts:
        - name: html
          mountPath: /html

  volumes:
    - name: html
      emptyDir: {}
