---
apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - name: env-container
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: APP_VERSION
          value: "1.0.0"